// import { LitElement, html, css } from 'lit'
// import { customElement, state } from 'lit/decorators.js'
// import '@material/mwc-checkbox'

import './app-container'
import './settings-dialog'
import './PairsManager'
import './ChangesManager'
import './KlinesManager'
import './pair-tag'
import './pair-strip'
import './pair-create-dialog'
import './volume-chart-element'
import './session-time-progress'
import './refresh-timer'

import '@material/mwc-snackbar'
import '@material/mwc-button'
import '@material/mwc-textfield'
import '@material/mwc-icon-button'
import '@material/mwc-icon'
import '@material/mwc-dialog'
import '@material/mwc-select'
import '@material/mwc-linear-progress'